name: taracert
services:
  certbot:
    volumes:
      - ./generate-cert.sh:/generate-cert.sh:ro
    environment:
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
    command: >
      sh -c "trap exit TERM; /generate-cert.sh; /deploy-hook.sh; echo Ready; sleep infinity"
